### ISSUE TITLE
Problem using krate command

### ISSUE THREAD

**Issue by sebgeekinside** [kublet/krate#2]
Using krate init or build commands on Windows or Linux do not return any message.
In order to the krate send command works, it could be useful to indicate into the README the executable krate file must be located into the folder ../<folder of the app> i.e. ../.pio.

**Comment by audreylim** [comment]
Thanks! We've updated the README and krate command. When you run `krate init`, you will see this on success:

```
Initialized files in test:
    src/
    platformio.ini

cd into test project and begin development
Happy coding!
```

See latest binaries [here](https://github.com/kublet/krate/releases/tag/v0.0.11).

You should still see an output text when you run `krate build` though, it will start building like this:

```
➜ krate build
Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (6.5.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)

.....
```

Or give an error like this:

```
➜ krate build
NotPlatformIOProjectError: Not a PlatformIO project. `platformio.ini` file has not been found in current working directory (Users/A/Code/krate). To initialize new project please use `platformio project init` command
```

Let me know if there is still no output.

EDIT: You're right, there's no output on Windows. Will look into it get back.

**Comment by sebgeekinside** [comment]
I just try to download the latest Windows binary [[krate_Linux_x86_64.tar.gz](https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_x86_64.tar.gz)](https://github.com/kublet/krate/releases/tag/v0.0.11) but Windows Defender block downloading the file because the Trojan spy Trojan:Win32/WacatacB!ml is detected!

**Comment by sebgeekinside** [comment]
Using the latest Linux krate binary [krate_Linux_arm64.tar.gz](https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_arm64.tar.gz)(https://github.com/kublet/krate/releases/tag/v0.0.11), using VS-Code - PlatformIO, when I run the command krate build or krate build -v to compile the hello project from [here](https://github.com/kublet/community/tree/main/apps/hello):
- There is no output text for this command,
- There is no firmware.bin binary file generated into .pio folder (just few files are populated into .pio folder).

Why the code bellow do not run correctly on my environnement?
`...
cmd := exec.Command("pio", "run")
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
cmd.Stdin = os.Stdin
...`

**Comment by audreylim** [comment]
> I just try to download the latest Windows binary [[krate_Linux_x86_64.tar.gz](https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_x86_64.tar.gz)](https://github.com/kublet/krate/releases/tag/v0.0.11) but Windows Defender block downloading the file because the Trojan spy Trojan:Win32/WacatacB!ml is detected!

I think the binary should be a Windows binary, not Linux.

> Using the latest Linux krate binary [krate_Linux_arm64.tar.gz](https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_arm64.tar.gz)(https://github.com/kublet/krate/releases/tag/v0.0.11), using VS-Code - PlatformIO, when I run the command krate build or krate build -v to compile the hello project

Are you running the binary on Windows or Linux?

> There is no output text for this command,

We're fixing the output text not showing up on Windows. Will have an update.

**Comment by sebgeekinside** [comment]
> > Using the latest Linux krate binary [krate_Linux_arm64.tar.gz](https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_arm64.tar.gz)(https://github.com/kublet/krate/releases/tag/v0.0.11), using VS-Code - PlatformIO, when I run the command krate build or krate build -v to compile the hello project
> 
> Are you running the binary on Windows or Linux?

First, I have ran the binary via VS-Code on Windows.
I have also try to ran the binary on Linux ([krate_Linux_arm64.tar.gz](https://github.com/kublet/krate/releases/download/v0.0.11/krate_Linux_arm64.tar.gz)).

Why the code bellow do not run correctly via VS-Code under Windows?
... cmd := exec.Command("pio", "run") cmd.Stdout = os.Stdout cmd.Stderr = os.Stderr cmd.Stdin = os.Stdin ...

**Comment by audreylim** [comment]
Hi @sebgeekinside , in VS Code/PIO, you need to run `krate build` within the PIO terminal, not the powershell. Open the PIO terminal by clicking on the terminal icon at the bottom of VS code.

![Screenshot 2024-07-21 053126](https://github.com/user-attachments/assets/e3288032-21eb-49b8-85c6-1b80446d39d0)
![Screenshot 2024-07-21 053145](https://github.com/user-attachments/assets/474eef4b-dc53-45e1-8e73-96306e94968d)

If you're running `krate` within the command prompt, you will need to make the PIO tools available system wide. Add the PIO tools to your PATH (see [docs](https://docs.platformio.org/en/latest/core/installation/shell-commands.html#windows)):

On Windows, search for System -> Advanced System Settings -> Environment Variables -> User variables for <your PC username> -> Path -> Edit -> New -> Add this: C:\Users\<your PC username>\.platformio\penv\Scripts.


![Screenshot 2024-07-21 053811](https://github.com/user-attachments/assets/7127b1d9-106b-4947-b57f-92d5be925057)

**Comment by audreylim** [comment]
You can also add to the Path environment variable the path to your downloaded krate binary to make krate.exe available from anywhere: eg. `C:\Users\A\Downloads\krate_Windows_x86_64`.

**Comment by sebgeekinside** [comment]
It works fine with your help!
Thanks! :-)
